<?php
// lang/en.php
$lang = [
    // Header
    'home' => 'Home',
    'about_us' => 'About us',
    'contact_us' => 'Contact us',
    'login' => 'Login',
    'register' => 'Register',
    'welcome_user' => 'Welcome',
    'logout' => 'Logout',
    'lang_switch' => 'Language',

    // Page <title>
    'site_tagline' => 'Empowering Modern Agriculture',

    // Preloader
    'preloader_title' => 'KisanX',

    // Hero Section
    'hero_title_harvesting' => 'Harvesting',
    'hero_title_the' => 'The',
    'hero_title_future' => 'Future',
    'hero_subtitle' => 'A premium platform connecting dedicated farmers with discerning buyers. Experience seamless trade, transparent pricing, and unparalleled quality, direct from the fields.',
    'hero_cta_button' => 'Explore The Harvest',

    // Categories
    'category_title' => 'Shop by Category',
    'category_vegetables' => 'Vegetables',
    'category_fruits' => 'Fruits',
    'category_grains' => 'Grains',
    'category_spices' => 'Spices',

    // Sections
    'topsales_title' => 'Top Selling Products',
    'allproducts_title' => 'All Available Products',
    'services_title' => 'Modern Platform Services',
    'community_title' => 'From Our Community',
    'cta_title' => 'Join a Growing Community',

    // Product Card
    'card_add_to_cart' => 'Add to cart',

    // Services
    'service_1_title' => 'Market Analytics',
    'service_1_desc' => 'Leverage data to predict market trends, optimize crop pricing, and maximize your profits with actionable insights.',
    'service_2_title' => 'Streamlined Logistics',
    'service_2_desc' => 'An efficient supply chain to deliver your produce with real-time tracking, ensuring freshness and reliability.',
    'service_3_title' => 'Secure Payments',
    'service_3_desc' => 'Experience peace of mind with fast, secure payment processing, ensuring trust and transparency in every transaction.',

    // Testimonials
    'community_1_quote' => '"This platform has truly changed how I run my farm. The market data is invaluable and has directly increased my income."',
    'community_1_author' => 'Rajesh Kumar',
    'community_1_role' => 'Grain Farmer, Punjab',
    'community_2_quote' => '"The logistics support is fantastic. My produce reaches the market fresher and faster, which my buyers really appreciate."',
    'community_2_author' => 'Priya Patel',
    'community_2_role' => 'Orchardist, Himachal',
    'community_3_quote' => '"Finally, a modern tool that understands the needs of a farmer. It\'s professional, easy to navigate, and very effective."',
    'community_3_author' => 'Anil Reddy',
    'community_3_role' => 'Spice Grower, Kerala',

    // CTA Section
    'cta_subtitle' => 'Become a part of the future of agriculture. Register your farm today to access a wider market, modern tools, and a network of passionate farmers.',
    'cta_button' => 'Register Your Farm',

    // Modal & Toast
    'toast_added_to_cart' => 'Added to cart!',
    'modal_title' => 'Login Required',
    'modal_subtitle' => 'Please log in or create an account to add items to your cart.',
    'modal_login_button' => 'Login',
    'modal_register_button' => 'Register',

    // --- About Us Page ---
    'about_page_title' => 'About Us — kisanX',
    'about_title' => 'Who',
    'about_title_span' => 'We Are',
    'about_intro_p1' => 'kisanX was founded on a simple yet powerful idea: to bridge the gap between the hardworking farmers of India and the end consumers. Established on <strong>September 27, 2025</strong>, in Pune, we saw a system where farmers\' profits were minimized by middlemen, while customers paid inflated prices. We are here to change that.',
    'about_intro_p2' => 'By leveraging technology, we have built a transparent, efficient, and fair ecosystem. We partner directly with agricultural communities to bring their fresh, authentic produce to homes and businesses, ensuring farmers get the value they deserve and customers get quality they can trust.',
    'about_mission_title' => 'Our Mission',
    'about_mission_p' => 'To empower Indian farmers by providing a direct and profitable market linkage, while delivering the freshest, highest-quality produce to consumers at fair prices through a seamless technology platform.',
    'about_vision_title' => 'Our Vision',
    'about_vision_p' => 'To become India\'s most trusted agricultural supply chain, creating a sustainable and transparent food ecosystem that benefits both the farmer and the consumer for generations to come.',
    'about_values_title' => 'Our Core',
    'about_values_title_span' => 'Values',
    'about_value_1_title' => 'Trust',
    'about_value_1_p' => 'We build lasting relationships based on fairness and reliability with our farmers, partners, and customers.',
    'about_value_2_title' => 'Transparency',
    'about_value_2_p' => 'From pricing to produce origin, we provide complete visibility, ensuring every transaction is clear and honest.',
    'about_value_3_title' => 'Technology',
    'about_value_3_p' => 'We use innovation to streamline logistics, ensure quality, and make fresh produce accessible to everyone.',
    'about_impact_title' => 'Our Impact',
    'about_impact_title_span' => 'in Numbers',
    'about_impact_1_p' => 'Farmers Empowered',
    'about_impact_2_p' => 'Average Increase in Farmer Income',
    'about_impact_3_p' => 'Tonnes of Fresh Produce Delivered',
    'about_team_title' => 'Meet Our',
    'about_team_title_span' => 'Team',
    'about_team_1_role' => 'Founder & CEO',
    'about_team_2_role' => 'Head of Operations',
    'about_team_3_role' => 'Technology Lead',
    'about_team_4_role' => 'Marketing Manager',
    'about_join_title' => 'Join the',
    'about_join_title_span' => 'Movement',
    'about_join_p' => 'Whether you are a farmer seeking a fair marketplace or a buyer looking for unparalleled freshness and quality, kisanX is your trusted partner. Become a part of a better food future today.',
    'about_join_btn_1' => 'Register as a Farmer',
    'about_join_btn_2' => 'Register as a Buyer',

    // --- Footer ---
    'footer_brand_subtitle' => 'Connecting farmers directly with consumers at wholesale prices. 🌱',
    'footer_quick_links' => 'Quick Links',
    'footer_products' => 'Our Products',
    'footer_support' => 'Support',
    'footer_faqs' => 'FAQs',
    'footer_policy' => 'Privacy Policy',
    'footer_terms' => 'Terms & Conditions',
    'footer_follow' => 'Follow Us',
    'footer_copyright' => 'All rights reserved. Designed by Anni.',

    // --- Contact Us Page ---
    'contact_page_title' => 'Contact Us — kisanX',
    'contact_title_1' => 'Get',
    'contact_title_2' => 'In',
    'contact_title_3' => 'Touch',
    'contact_subtitle' => 'We\'re here to help and answer any question you might have. We look forward to hearing from you. You can reach us through the form, by phone, or by visiting our office.',
    'contact_form_title' => 'Send us a Message',
    'contact_form_name' => 'Your Name',
    'contact_form_email' => 'Your Email',
    'contact_form_message' => 'Your Message',
    'contact_form_placeholder' => 'Let us know how we can help...',
    'contact_form_button' => 'Send Message',
    'contact_form_success' => '✅ Thank you for your message! We will get back to you soon.',
    'contact_details_title' => 'Contact Details',
    'contact_details_addr_title' => 'Office Address:',
    'contact_details_addr_p' => '123 Agri-Tech Park, Viman Nagar, Pune, Maharashtra, 411014',
    'contact_details_hours_title' => 'Business Hours:',
    'contact_details_hours_p' => 'Monday - Saturday: 9:00 AM - 6:00 PM',
    'contact_details_inq_title' => 'General Inquiries:',
    'contact_details_part_title' => 'Farmer Partnerships:',
    'contact_details_b2b_title' => 'Bulk & B2B Orders:',
    'contact_location_title' => 'Our Location',
    'contact_faq_title' => 'Frequently Asked Questions',
    'contact_faq_1_q' => 'How do I register as a farmer?',
    'contact_faq_1_a' => 'You can register by clicking the "Register" button on our homepage and selecting the "Farmer" option. You will need to provide basic information about your farm, location, and the types of produce you grow.',
    'contact_faq_2_q' => 'What are the benefits of selling through kisanX?',
    'contact_faq_2_a' => 'By selling through our platform, you get direct access to a wide market of buyers, fair and transparent pricing without middlemen, and faster payments. We also provide logistical support to ensure your produce reaches the buyer efficiently.',
    'contact_faq_3_q' => 'How is the quality of the produce ensured?',
    'contact_faq_3_a' => 'We have a multi-step quality assurance process. Our team works with farmers to establish best practices, and we perform quality checks at our collection centers before dispatching any produce to the buyer.',
    'contact_faq_4_q' => 'Can I place a bulk order for my business?',
    'contact_faq_4_a' => 'Absolutely! We specialize in B2B and bulk orders for restaurants, hotels, and retailers. Please contact our sales team at <strong>sales@kisanX.com</strong> for a customized quote and delivery schedule.',

    // --- Login Page ---
    'login_page_title' => 'Login — kisanX',
    'login_title' => 'Login',
    'login_reg_success' => 'Registration successful. Please login.',
    'login_email_placeholder' => 'Email',
    'login_password_placeholder' => 'Password',
    'login_button' => 'Login',
    'login_no_account' => 'Don\'t have an account?',
    'login_register_link' => 'Register',
    'error_missing_credentials' => 'Please provide email and password.',
    'error_invalid_credentials' => 'Invalid credentials.',

    // --- Register Page ---
    'register_page_title' => 'Create an Account — kisanX',
    'register_title' => 'Create Account',
    'register_name_placeholder' => 'Full Name',
    'register_email_placeholder' => 'Email',
    'register_password_placeholder' => 'Password (min 8 chars)',
    'register_confirm_pass_placeholder' => 'Confirm Password',
    'register_role_label' => 'Register as a:',
    'register_role_buyer' => 'Buyer',
    'register_role_farmer' => 'Farmer',
    'register_button' => 'Register',
    'register_already_account' => 'Already have an account?',
    'register_login_link' => 'Login',

    // --- Register Page Errors ---
    'error_name_required' => 'Full name is required.',
    'error_email_invalid' => 'A valid email is required.',
    'error_password_short' => 'Password must be at least 8 characters.',
    'error_password_mismatch' => 'Passwords do not match.',
    'error_role_required' => 'Please select a role.',
    'error_email_exists' => 'An account with this email already exists.',

    // --- Products Page ---
    'products_page_title' => 'Products — kisanX',
    'toast_wishlist_add' => 'Item added to wishlist!',
    'toast_wishlist_remove' => 'Item removed from wishlist!',
    'toast_cart_update' => 'Product quantity updated in cart!',
    'toast_cart_add' => 'Product added to cart successfully!',
    'sidebar_dashboard' => 'Dashboard',
    'sidebar_wishlist' => 'Wishlist',
    'sidebar_cart' => 'Cart',
    'sidebar_orders' => 'Orders',
    'products_search_title_span' => 'Search',
    'products_search_title' => 'Products',
    'products_search_placeholder' => 'Search vegetables, fruits...',
    'products_all_categories' => 'All categories',
    'products_search_button' => 'Search',
    'products_results_title' => 'Results for',
    'card_add_wishlist' => '♡ Add to Wishlist',
    'card_in_wishlist' => '♥ In Wishlist',
    'products_no_results' => 'No products found matching your search criteria.',
    'products_all_title_span' => 'All',
    'products_all_title' => 'Products',
    'products_modal_subtitle' => 'Please log in or create an account to add items to your cart or wishlist.',
    'products_category_modal_title' => 'Select a Category',

    // --- Cart Page ---
    'cart_page_title' => 'Your Cart - kisanX',
    'cart_title' => 'Your Shopping',
    'cart_title_span' => 'Cart',
    'cart_empty_message' => 'Your cart is currently empty. Time to add some fresh produce!',
    'cart_continue_shopping' => 'Continue Shopping',
    'cart_item_price' => 'Price:',
    'cart_remove_item' => 'Remove',
    'cart_summary_title' => 'Order Summary',
    'cart_summary_subtotal' => 'Subtotal',
    'cart_summary_shipping' => 'Shipping',
    'cart_summary_shipping_free' => 'FREE',
    'cart_summary_total' => 'Grand Total',
    'cart_checkout_button' => 'Proceed to Checkout',
    'alert_cart_update_error_prefix' => 'Error updating quantity:',
    'alert_cart_update_error_generic' => 'An error occurred while updating the cart.',

    // --- Checkout Page ---
    'checkout_page_title' => 'Checkout - kisanX',
    'checkout_title' => 'Checkout',
    'checkout_title_span' => 'Process',
    'checkout_shipping_title' => 'Shipping Details',
    'checkout_form_name' => 'Full Name',
    'checkout_form_name_placeholder' => 'Enter your full name',
    'checkout_form_address' => 'Full Address',
    'checkout_form_address_placeholder' => 'Enter your complete street address, city, and pincode',
    'checkout_form_phone' => 'Phone Number',
    'checkout_form_phone_placeholder' => 'Enter a valid 10-digit phone number',
    'checkout_form_button' => 'Place Order',
    'checkout_summary_title' => 'Your Order',
    'checkout_summary_title_span' => 'Summary',
    'checkout_summary_product' => 'Product',
    'checkout_summary_qty' => 'Qty',
    'checkout_summary_subtotal' => 'Subtotal',
    'checkout_summary_total' => 'Grand Total',

    // --- Checkout Page Errors/Info ---
    'checkout_error_all_fields' => 'All shipping fields are required!',
    'checkout_error_failed' => 'Checkout failed. Please try again.',
    'checkout_cart_empty_title' => 'Your cart is empty',
    'checkout_cart_empty_message' => 'You cannot proceed to checkout without items in your cart.',
    'checkout_cart_empty_link' => 'Go Shopping',

    // --- User Dashboard Page ---
    'user_dashboard_title' => 'User Dashboard - kisanX',
    'user_dashboard_welcome' => 'Welcome,',
    'user_dashboard_search_title_span' => 'Search',
    'user_dashboard_search_title' => 'Products',
    'user_dashboard_search_placeholder' => 'Search vegetables, fruits...',
    'user_dashboard_all_categories' => 'All categories',
    'user_dashboard_search_button' => 'Search',
    'user_dashboard_shop_by_title_span' => 'Shop by',
    'user_dashboard_shop_by_title' => 'Category',
    'user_dashboard_category_veg' => 'Vegetables',
    'user_dashboard_category_fruits' => 'Fruits',
    'user_dashboard_category_grains' => 'Grains',
    'user_dashboard_category_spices' => 'Spices',
    'user_dashboard_available_title_span' => 'Available',
    'user_dashboard_available_title' => 'Products',
    'user_dashboard_bestsellers_title_span' => 'Best',
    'user_dashboard_bestsellers_title' => 'Sellers',
    'user_dashboard_orders_title_span' => 'Your',
    'user_dashboard_orders_title' => 'Orders',
    'user_dashboard_no_orders' => 'You have not placed any orders yet.',
    'user_dashboard_order_table_id' => 'Order #',
    'user_dashboard_order_table_items' => 'Items',
    'user_dashboard_order_table_total' => 'Total (₹)',
    'user_dashboard_order_table_status' => 'Status',
    'user_dashboard_order_table_date' => 'Date',
    'user_dashboard_order_table_track' => 'Track',
    'user_dashboard_track_button' => 'Track',
    'user_dashboard_modal_remove_title' => 'Remove Item?',
    'user_dashboard_modal_remove_p' => 'Are you sure you want to remove this item from your wishlist?',
    'user_dashboard_modal_cancel_button' => 'Cancel',
    'user_dashboard_modal_remove_button' => 'Yes, Remove',
    'user_dashboard_modal_success_title' => 'Success!',
    'user_dashboard_modal_ok_button' => 'OK',
    'user_dashboard_modal_category_title' => 'Select a Category',

    // --- Farmer Dashboard Page ---
    'farmer_dashboard_title' => 'Farmer Dashboard - kisanX',
    'farmer_sidebar_dashboard' => 'Dashboard',
    'farmer_sidebar_add_product' => 'Add Product',
    'farmer_sidebar_my_products' => 'My Products',
    'farmer_sidebar_analytics' => 'Sales Analytics',
    'farmer_sidebar_logout' => 'Logout',
    'farmer_header_greeting_morning' => 'Good Morning,',
    'farmer_header_greeting_afternoon' => 'Good Afternoon,',
    'farmer_header_greeting_evening' => 'Good Evening,',
    'farmer_header_title' => 'Farmer Dashboard',
    'farmer_header_search_placeholder' => 'Search products by name...',
    'farmer_header_export_button' => 'Export',
    'farmer_header_dark_mode' => 'Dark Mode',
    'farmer_header_light_mode' => 'Light Mode',
    'farmer_stats_today_revenue' => 'Today\'s Revenue',
    'farmer_stats_today_orders' => 'Today\'s Orders',
    'farmer_stats_total_revenue' => 'Total Revenue',
    'farmer_stats_total_sold' => 'Total Items Sold',
    'farmer_model_title' => 'Your Digital Farmstead 🚜',
    'farmer_top_selling_title' => 'Top 5 Selling Products',
    'farmer_top_selling_no_data' => 'No sales data yet.',
    'farmer_top_selling_sold' => 'sold',
    'farmer_low_stock_title' => 'Low Stock Alerts',
    'farmer_low_stock_no_data' => 'Everything is well-stocked!',
    'farmer_low_stock_left' => 'left',
    'farmer_live_activity_title' => 'Live Product Interest',
    'farmer_live_activity_waiting' => 'Waiting for customer activity...',
    'farmer_live_activity_added' => 'A customer added',
    'farmer_live_activity_to_basket' => 'to their basket.',
    'farmer_recent_orders_title' => 'Recent Orders',
    'farmer_recent_orders_no_data' => 'No recent orders found.',
    'farmer_table_order_id' => 'Order ID',
    'farmer_table_customer' => 'Customer',
    'farmer_table_product' => 'Product',
    'farmer_table_qty' => 'Qty',
    'farmer_table_price' => 'Price',
    'farmer_table_total' => 'Total',
    'farmer_table_date' => 'Date',
    'farmer_add_product_title' => 'Add New Product',
    'farmer_add_product_name' => 'Product Name',
    'farmer_add_product_category' => 'Category',
    'farmer_add_product_select_cat' => '--Select Category--',
    'farmer_add_product_price' => 'Price (₹)',
    'farmer_add_product_qty' => 'Quantity in Stock',
    'farmer_add_product_discount' => 'Discount %',
    'farmer_add_product_desc' => 'Description',
    'farmer_add_product_image' => 'Product Image',
    'farmer_add_product_image_preview' => 'Image Preview',
    'farmer_add_product_button' => 'Add Product',
    'farmer_add_product_success' => 'Product added successfully!',
    'farmer_add_product_error' => 'Name and price required.',
    'farmer_my_products_title' => 'My Products',
    'farmer_my_products_no_data' => 'You have not added any products yet.',
    'farmer_my_products_stock' => 'Stock:',
    'farmer_my_products_discount_off' => '% OFF',
    'farmer_analytics_title' => 'Sales Analytics',
    'farmer_analytics_no_data' => 'No sales data available to generate charts.',
    'farmer_analytics_pie_label_1' => 'Items Sold',
    'farmer_analytics_pie_label_2' => 'Items in Stock',
    'farmer_analytics_bar_label' => 'Total Revenue per Product (₹)',
    'farmer_analytics_line_label' => 'Daily Revenue',
    'farmer_notification_export' => 'Export ready — downloaded!',

    // --- FAQ Page ---
    'faq_page_title' => 'Frequently Asked Questions — kisanX',
    'faq_title_span' => 'Frequently Asked',
    'faq_title' => 'Questions',
    'faq_subtitle' => 'Have questions? We\'re here to help. Find answers to common queries about our platform, services, and how we connect farmers and buyers.',
    'faq_category_buyers' => 'For Buyers',
    'faq_q_quality' => 'How is the quality of the produce ensured?',
    'faq_a_quality' => 'We have a multi-step quality assurance process. Our team works directly with farmers to establish best practices for growing and harvesting. All produce then undergoes a thorough quality check at our local collection centers before it is packaged and dispatched to you, ensuring it meets our high standards for freshness and quality.',
    'faq_q_b2b' => 'Can I place a bulk order for my business (B2B)?',
    'faq_a_b2b' => 'Absolutely! We specialize in B2B and bulk orders for restaurants, hotels, retailers, and food processors. Please visit our \'Contact Us\' page and get in touch with our sales team (at sales@kisanX.com) for customized quotes, volume pricing, and dedicated delivery schedules.',
    'faq_q_delivery' => 'What is the delivery process and timing?',
    'faq_a_delivery' => 'We offer streamlined logistics to ensure maximum freshness. Delivery times vary by location and order size. For most city locations, we offer next-day delivery for orders placed before our cut-off time. You will receive a confirmation and tracking information once your order is dispatched.',
    'faq_category_farmers' => 'For Farmers',
    'faq_q_farmer_reg' => 'How do I register as a farmer?',
    'faq_a_farmer_reg' => 'You can register by clicking the "Register" button on our homepage and selecting the "Farmer" option. You will need to provide basic information about your farm, location, contact details, and the types of produce you grow. Our team will then review your application and contact you for verification.',
    'faq_q_farmer_benefits' => 'What are the benefits of selling through kisanX?',
    'faq_a_farmer_benefits' => 'By selling through our platform, you get direct access to a wide market of verified buyers, which means no more middlemen. This results in fair, transparent pricing and typically a 20-30% increase in your income. We also provide payments directly to your account faster than traditional methods.',
    'faq_q_farmer_list' => 'How do I list my products for sale?',
    'faq_a_farmer_list' => 'Once you are a verified farmer on our platform, you will get access to your Farmer Dashboard. From there, you can easily add new products, set your own prices, update your available stock (quantity), and add photos and descriptions for your produce.',
    'faq_category_general' => 'General Questions',
    'faq_q_payment' => 'What payment methods do you accept?',
    'faq_a_payment' => 'We accept a wide range of payment methods for your convenience, including all major Credit/Debit Cards (Visa, MasterCard, RuPay), UPI (PhonePe, Google Pay, Paytm), and Net Banking from all major banks.',
    'faq_q_returns' => 'What is your policy on returns or bad produce?',
    'faq_a_returns' => 'Your satisfaction is our priority. If you receive any produce that does not meet your expectations, please contact our customer support within 24 hours of delivery with a photo of the item. We will arrange for a prompt replacement or a full refund for the item.',
    'faq_cta_title_span' => 'Still have',
    'faq_cta_title' => 'questions?',
    'faq_cta_subtitle' => 'If you can\'t find the answer you\'re looking for, our team is happy to help. Get in touch with us directly.',
    'faq_cta_button' => 'Contact Us',

    // --- Wishlist Page ---
    'wishlist_page_title' => 'My Wishlist - kisanX',
    'wishlist_title_span' => 'My',
    'wishlist_title' => 'Wishlist',
    'wishlist_empty_message' => 'Your wishlist is currently empty.',
    'wishlist_empty_subtitle' => 'Browse products and click the "♡ Add to Wishlist" button to save your favorites here.',
    'wishlist_browse_products' => 'Browse Products',
    'wishlist_removed_toast' => 'Item removed from wishlist!',
    'wishlist_added_cart_toast' => 'Item added to cart!',

    // --- Privacy Policy Page ---
    'policy_page_title' => 'Privacy Policy - kisanX',
    'policy_title_span' => 'Privacy',
    'policy_title' => 'Policy',
    'policy_last_updated' => 'Last Updated: 1 Nov 2025',
    'policy_intro_title' => 'Introduction',
    'policy_intro_p1' => 'Welcome to kisanX. We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website and use our services.',
    'policy_info_title' => 'Information We Collect',
    'policy_info_p1' => 'We may collect personal information from you in various ways:',
    'policy_info_li1' => '<strong>Personal Data:</strong> Personally identifiable information, such as your name, shipping address, email address, and telephone number, and user type (farmer/buyer) that you voluntarily give to us when you register.',
    'policy_info_li2' => '<strong>Financial Data:</strong> We do not store any credit card or payment information. All payment data is handled and processed securely by our third-party payment gateways.',
    'policy_info_li3' => '<strong>Derivative Data:</strong> Information our servers automatically collect, such as your IP address, browser type, and pages you have visited.',
    'policy_usage_title' => 'How We Use Your Information',
    'policy_usage_p1' => 'Having accurate information permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you to:',
    'policy_usage_li1' => 'Create and manage your account.',
    'policy_usage_li2' => 'Process your orders, payments, and deliveries.',
    'policy_usage_li3' => 'Facilitate direct communication between verified farmers and buyers.',
    'policy_usage_li4' => 'Notify you of updates and new products.',
    'policy_sharing_title' => 'Disclosure of Your Information',
    'policy_sharing_p1' => 'We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information unless we provide users with advance notice. This does not include:',
    'policy_sharing_li1' => 'Website hosting partners and other parties who assist us in operating our website, conducting our business, or serving our users, so long as those parties agree to keep this information confidential.',
    'policy_sharing_li2' => 'Verified Farmers/Buyers you choose to transact with, limited to the information necessary to complete the transaction (e.g., name, address for delivery).',
    'policy_security_title' => 'Security of Your Information',
    'policy_security_p1' => 'We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable.',
    'policy_contact_title' => 'Contact Us',
    'policy_contact_p1' => 'If you have questions or comments about this Privacy Policy, please contact us at:',

    // --- Terms & Conditions Page ---
    'terms_page_title' => 'Terms & Conditions - kisanX',
    'terms_title_span' => 'Terms &',
    'terms_title' => 'Conditions',
    'terms_last_updated' => 'Last Updated: 1 Nov 2025',
    'terms_agreement_title' => '1. Agreement to Terms',
    'terms_agreement_p1' => 'These Terms and Conditions constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and kisanX , concerning your access to and use of the kisanX website as well as any other media form related. You agree that by accessing the site, you have read, understood, and agree to be bound by all of these Terms and Conditions.',
    'terms_platform_title' => '2. The Platform',
    'terms_platform_p1' => 'kisanX is a technology platform that connects farmers directly with buyers (consumers and businesses). We are a marketplace facilitator and are not directly involved in the farming or production of goods. We provide services such as logistics, payment processing, and quality assurance to facilitate a transparent and efficient transaction.',
    'terms_accounts_title' => '3. User Accounts',
    'terms_accounts_p1' => 'You must register for an account to use most features. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate.',
    'terms_farmer_title' => '4. Terms for Farmers',
    'terms_farmer_li1' => 'You must be a verified farmer to sell products.',
    'terms_farmer_li2' => 'You are responsible for the accuracy of your product listings, including quantity, description, and origin.',
    'terms_farmer_li3' => 'You agree to adhere to the quality standards and best practices as communicated by kisanX.',
    'terms_farmer_li4' => 'Payments for your fulfilled orders will be processed and transferred to your registered bank account per the payment cycle defined by us.',
    'terms_buyer_title' => '5. Terms for Buyers',
    'terms_buyer_li1' => 'You agree to provide accurate shipping and contact information for the fulfillment of your orders.',
    'terms_buyer_li2' => 'Payment must be completed in full at the time of placing the order through our provided payment gateways.',
    'terms_buyer_li3' => 'If you receive produce that is not up to standard, you must report it within 24 hours of delivery with photographic evidence to be eligible for a refund or replacement.',
    'terms_liability_title' => '6. Limitation of Liability',
    'terms_liability_p1' => 'In no event will we or our directors or employees be liable to you or any third party for any direct, indirect, consequential, exemplary, incidental, special, or punitive damages arising from your use of the site or our services.',
    'terms_governing_title' => '7. Governing Law',
    'terms_governing_p1' => 'These Terms shall be governed by and defined following the laws of India. kisanX and yourself irrevocably consent that the courts of Pune, Maharashtra shall have exclusive jurisdiction to resolve any dispute which may arise in connection with these terms.',

    // --- Orders Page ---
    'orders_page_title' => 'Your Orders - kisanX',
    'orders_title_span' => 'My',
    'orders_title' => 'Orders',
    'orders_active_title' => 'Active Orders',
    'orders_no_active' => 'You have no active orders.',
    'orders_table_header_id' => 'Order #',
    'orders_table_header_items' => 'Items',
    'orders_table_header_total' => 'Total (₹)',
    'orders_table_header_status' => 'Status',
    'orders_table_header_date' => 'Date',
    'orders_table_header_actions' => 'Actions',
    'orders_status_pending' => 'Pending',
    'orders_status_delivered' => 'Delivered',
    'orders_status_cancelled' => 'Cancelled',
    'orders_action_cancel' => 'Cancel',
    'orders_cancelled_title' => 'Cancelled Orders',
    'orders_no_cancelled' => 'You have no cancelled orders.',
    'orders_modal_title' => 'Reason for Cancellation',
    'orders_modal_reason1' => 'Ordered by mistake',
    'orders_modal_reason2' => 'Found cheaper elsewhere',
    'orders_modal_reason3' => 'Delivery taking too long',
    'orders_modal_reason4' => 'Other',
    'orders_modal_placeholder' => 'Please specify your reason...',
    'orders_modal_close' => 'Close',
    'orders_modal_confirm' => 'Confirm Cancellation',
    'orders_modal_alert' => 'Please select or enter a reason for cancellation.',

    // --- Track Order Page ---
    'track_page_title' => 'Track Your Orders - kisanX',
    'track_title_span' => 'Track Your',
    'track_title' => 'Orders',
    'track_no_orders' => 'You haven\'t placed any orders yet.',
    'track_start_shopping' => 'Start Shopping',
    'track_order_id' => 'Order #',
    'track_status_pending' => 'Pending',
    'track_status_processing' => 'Processing',
    'track_status_dispatched' => 'Dispatched',
    'track_status_delivered' => 'Delivered',
    'track_status_cancelled' => 'Cancelled',
    'track_estimated_delivery' => 'Estimated Delivery:',
    'track_step_placed' => 'Placed',
    'track_step_processing' => 'Processing',
    'track_step_dispatched' => 'Dispatched',
    'track_step_delivered' => 'Delivered',
    'track_live_tracking' => 'Live Tracking (Simulation)',
    'track_shipping_to' => 'Shipping To',
    'track_view_details' => 'View Details',

    // --- Theme Toggler ---
    'theme_light_mode' => 'Light Mode',
    'theme_dark_mode' => 'Dark Mode',

    // --- News Page ---
    'news_menu' => 'News',
    'news_page_title' => 'Agri News — KisanX',
    'news_hero_title' => 'Latest Agriculture News',
    'news_hero_subtitle' => 'Stay updated with the latest trends in farming, market prices, government schemes, and technology.',
    'news_read_more' => 'Read Full Article',
    'news_source' => 'Source:',
    'news_published' => 'Published:',
    'news_category_tech' => 'Farm Tech',
    'news_category_price' => 'Market Price',
    'news_category_policy' => 'Govt Policy',
    'news_no_data' => 'No news articles available at the moment.',
];
?>